In [13]:
import numpy as np

lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
arreglo = np.array(lista)
arreglo


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
type(arreglo)

numpy.ndarray

In [4]:
arreglo.dtype

dtype('int32')

In [5]:

np.array(arreglo,dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [6]:
arreglonuevo =np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
promedio = np.mean(arreglo) #el mean puede usarse con lo ya aprendido (listas, tuplas, diccionarios, etc.)
promedio

5.5

In [8]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio

array([0.01675573, 0.87558133, 0.87662616, 0.58092722, 0.64534322,
       0.80709409, 0.19715827, 0.80204091, 0.35444023, 0.74863573])