In [9]:
import numpy as np

lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
arreglo = np.array(lista)
arreglo


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
type(arreglo)

In [18]:
arreglo.dtype

dtype('int32')

In [17]:

np.array(arreglo,dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [41]:
arreglonuevo =np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
promedio = np.mean(arreglo) #el mean puede usarse con lo ya aprendido (listas, tuplas, diccionarios, etc.)
promedio

5.5

In [42]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio

array([0.20257949, 0.20454629, 0.35184575, 0.26388634, 0.21064324,
       0.45657732, 0.51941992, 0.22407225, 0.41067074, 0.90169224])